services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes:
      - ./database:/docker-entrypoint-initdb.d
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app-net

  backend:
    image: node:20-alpine
    working_dir: /app
    mem_limit: 2g
    command: >
      sh -c "
      npm ci &&
      npx nest start --watch
      "
    volumes:
      - ./backend:/app
      - backend_node_modules:/app/node_modules
    ports:
      - "3001:3001"
    env_file:
      - .env
    environment:
      - NODE_ENV=${NODE_ENV}
      - NODE_OPTIONS=${NODE_OPTIONS}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      - PORT=${PORT}
      - do_spaces_endpoint=${do_spaces_endpoint}
      - do_spaces_region=${do_spaces_region}
      - do_spaces_bucket=${do_spaces_bucket}
      - do_spaces_key=${do_spaces_key}
      - do_spaces_secret=${do_spaces_secret}
    depends_on:
      - db
      - minio
      - createbuckets
    networks:
      - app-net

  frontend:
    mem_limit: 4g
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    command: >
      sh -c "npm run dev -- --port 3000 --hostname 0.0.0.0"
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=${NODE_ENV}
      - CHOKIDAR_USEPOLLING=${CHOKIDAR_USEPOLLING}
      - CHOKIDAR_INTERVAL=${CHOKIDAR_INTERVAL}
      - WATCHPACK_POLLING=${WATCHPACK_POLLING}
      - NODE_OPTIONS=${NODE_OPTIONS}
    working_dir: /app
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
      - frontend_next_cache:/app/.next
    depends_on:
      - backend
    networks:
      - app-net

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
      - backend
    networks:
      - app-net

  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    networks:
      - app-net

  createbuckets:
    image: minio/mc:latest
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      echo 'Waiting for MinIO to be ready...';
      sleep 5;
      /usr/bin/mc alias set myminio http://minio:9000 ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD};
      /usr/bin/mc mb myminio/${do_spaces_bucket} --ignore-existing;
      /usr/bin/mc anonymous set public myminio/${do_spaces_bucket};
      /usr/bin/mc ls myminio/${do_spaces_bucket};
      echo 'Bucket setup complete';
      exit 0;
      "
    networks:
      - app-net

volumes:
  mysql_data:
  minio_data:
  backend_node_modules:
  frontend_node_modules:
  frontend_next_cache:

networks:
  app-net:
    driver: bridge
